# -*- coding: utf-8 -*-
"""Copy of DATA CAPSTONE FINAL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14p7weHtp9HUa-ZIq0M6OHjuI8muyrL3E

# Business Understanding
Latar Belakang
...

# Business Question
1. Bagaimana distribusi karakteristik mahasiswa berdasarkan jurusan, bidang minat, soft skill, pengalaman, dan sertifikasi yang dimiliki?
2. Karier apa yang paling banyak direkomendasikan berdasarkan karakteristik mahasiswa dalam dataset?
3. Bagaimana hubungan antara latar belakang akademik (jurusan) dan rekomendasi karier yang diberikan?

# CAPSTONE PROJECT
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme()

"""# LOAD DATASET"""

df = pd.read_csv('/content/Data Karir dan Jurusan.csv')

print("Jumlah data awal:", len(df))
df.head()

"""# ANALISIS AWAL DATASET"""

df.info()

"""# CEK MISSING VALUE"""

print(df.isnull().sum())

"""# CEK DUPLIKASI"""

print("Jumlah duplikasi:", df.duplicated().sum())

"""# CEK STATISTIK NUMERIK"""

df.describe()

"""# BERSIHKAN SPASI BERLEBIH"""

for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].astype(str).str.strip()

"""# MENYERAGAMKAN HURUF"""

for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.title()

"""# PERBAIKI TYPO"""

perbaikan_karier = {
    "Data Scintist": "Data Scientist",
    "Softwere Engineer": "Software Engineer",
    "Busines Analyst": "Business Analyst"
}

df["Rekomendasi_Karier"] = df["Rekomendasi_Karier"].replace(perbaikan_karier)

"""STANDARISASI NILAI YA/TIDAK"""

kolom_ya_tidak = [
    "Pengalaman_Magang",
    "Pengalaman_Organisasi",
    "Pengalaman_Kompetisi"
]

for col in kolom_ya_tidak:
    df[col] = df[col].replace({
        "Ya":"Ya",
        "YA":"Ya",
        "ya":"Ya",
        "Tidak":"Tidak",
        "TIDAK":"Tidak",
        "tidak":"Tidak"
    })

"""MENGATASI MISSING VALUE"""

numerik = df.select_dtypes(include=np.number).columns

for col in numerik:
    df[col] = df[col].fillna(df[col].median())

kategorikal = df.select_dtypes(include='object').columns

for col in kategorikal:
    df[col] = df[col].fillna(df[col].mode()[0])

"""# HAPUS DUPLIKASI"""

print("Duplikasi sebelum:", df.duplicated().sum())

df = df.drop_duplicates()

print("Duplikasi sesudah:", df.duplicated().sum())

"""HAPUS OUTLIER IPK"""

print("Jumlah data sebelum:", len(df))

df = df[(df["IPK"] >= 0) & (df["IPK"] <= 4)]

print("Jumlah data sesudah:", len(df))

"""# CEKHASIL CLEANING"""

print("\nMissing Value:")
print(df.isnull().sum())

print("\nDuplikasi:")
print(df.duplicated().sum())

print("\nUkuran Dataset:")
print(df.shape)

"""# SIMPAN DATASET BERSIH"""

df.to_csv(
    "Career_Recommendation_Cleaned.csv",
    index=False
)

print("Dataset berhasil disimpan")

"""# DOWNLOAD HASIL"""

from google.colab import files

files.download(
    "Career_Recommendation_Cleaned.csv"
)

"""# Gathering Data"""

Career_Recommendation_Cleaned_df = pd.read_csv('Career_Recommendation_Cleaned.csv')
Career_Recommendation_Cleaned_df.head()

"""# Assesing Data"""

Career_Recommendation_Cleaned_df.info()

Career_Recommendation_Cleaned_df.isna().sum()

print("Jumlah duplikasi:", Career_Recommendation_Cleaned_df.duplicated().sum())
Career_Recommendation_Cleaned_df.describe()

(Career_Recommendation_Cleaned_df == 'Nan').sum()

"""# Cleaning Data"""

Career_Recommendation_Cleaned_df.replace('Nan', np.nan, inplace=True)

Career_Recommendation_Cleaned_df.isna().sum()

## Missing Value

# Hapus missing pada target
Career_Recommendation_Cleaned_df.dropna(
    subset=['Rekomendasi_Karier'],
    inplace=True
)

# Isi missing value fitur kategorikal dengan modus
for col in Career_Recommendation_Cleaned_df.select_dtypes(include='object').columns:
    if col != 'Rekomendasi_Karier':
        Career_Recommendation_Cleaned_df[col] = (
            Career_Recommendation_Cleaned_df[col]
            .fillna(Career_Recommendation_Cleaned_df[col].mode()[0])
        )

# Cek hasil
print(Career_Recommendation_Cleaned_df.isna().sum())

(Career_Recommendation_Cleaned_df == 'Nan').sum()

# =========================================================
# MENYIMPAN DATA CLEAN KE CSV BARU
# =========================================================

df_clean = Career_Recommendation_Cleaned_df.copy()

df_clean.to_csv(
    'New_Career_Recommendation_Cleaned.csv',
    index=False
)

print("Dataset clean berhasil disimpan!")

df_clean = pd.read_csv('New_Career_Recommendation_Cleaned.csv')

df_clean.info()
df_clean.isna().sum()
df_clean.duplicated().sum()

"""# EDA"""

New_Career_Recommendation_Cleaned_df = pd.read_csv('New_Career_Recommendation_Cleaned.csv')
New_Career_Recommendation_Cleaned_df.describe(include="all")

"""## Analisis Jurusan Mahasiswa"""

plt.figure(figsize=(10,5))

Career_Recommendation_Cleaned_df['Jurusan'] \
    .value_counts() \
    .head(10) \
    .sort_values() \
    .plot(kind='barh')

plt.title('10 Jurusan Terbanyak')
plt.xlabel('Jumlah Mahasiswa')
plt.ylabel('Jurusan')
plt.show()

"""### Insight
Jurusan yang paling banyak muncul dalam dataset adalah jurusan hukum, sedangkan jurusan dengan jumlah mahasiswa paling sedikit pada kelompok 10 besar adalah jurusan film. Hal ini menunjukkan bahwa dataset didominasi oleh mahasiswa dari bidang studi tertentu, namun tetap mencakup berbagai latar belakang akademik yang beragam.

## Analisis Bidang Minat
"""

plt.figure(figsize=(10,5))

Career_Recommendation_Cleaned_df['Bidang_Minat'] \
    .value_counts() \
    .plot(kind='bar')

plt.title('Distribusi Bidang Minat')
plt.xlabel('Bidang Minat')
plt.ylabel('Jumlah Mahasiswa')

plt.xticks(rotation=45)

plt.show()

"""### Insight
Bidang minat yang paling banyak dipilih adalah keuangan, sedangkan yang paling sedikit adalah pendidikan. Hal ini menunjukkan kecenderungan minat mahasiswa terhadap sektor tertentu yang dianggap memiliki prospek karier yang menarik.

## Analisis IPK
"""

plt.figure(figsize=(8,5))

sns.histplot(
    data=Career_Recommendation_Cleaned_df,
    x='IPK',
    bins=20,
    kde=True
)

plt.title('Distribusi IPK Mahasiswa')
plt.xlabel('IPK')
plt.ylabel('Frekuensi')

plt.show()

"""### Insight
Distribusi IPK mahasiswa berada pada rentang 2,8–4,0 dan cenderung merata. Frekuensi tertinggi berada di sekitar IPK 3,3–3,4, menunjukkan bahwa sebagian besar mahasiswa memiliki performa akademik yang baik. Distribusi yang relatif seimbang mengindikasikan tidak adanya dominasi nilai IPK pada rentang tertentu.

## Boxplot IPK
"""

plt.figure(figsize=(8,4))

sns.boxplot(
    x=Career_Recommendation_Cleaned_df['IPK']
)

plt.title('Boxplot IPK')

plt.show()

"""### Insight
Boxplot menunjukkan bahwa nilai IPK mahasiswa berada pada rentang sekitar 2,75 hingga 4,00 dengan median sekitar 3,4. Sebanyak 50% data berada pada rentang 3,1 hingga 3,7 (IQR), yang menunjukkan variasi IPK tergolong sedang. Tidak terlihat adanya outlier, sehingga distribusi IPK relatif bersih dan tidak terdapat nilai yang menyimpang jauh dari mayoritas data. Hal ini mengindikasikan bahwa performa akademik mahasiswa dalam dataset cukup konsisten dan representatif terhadap keseluruhan populasi.

## Analisis Soft Skill

### Rata-rata Soft Skill
"""

softskill = [
    'Kepemimpinan',
    'Komunikasi',
    'Kerja_Tim',
    'Kreativitas',
    'Berpikir_Kritis',
    'Pemecahan_Masalah'
]

plt.figure(figsize=(10,5))

Career_Recommendation_Cleaned_df[softskill] \
    .mean() \
    .sort_values() \
    .plot(kind='barh')

plt.title('Rata-rata Soft Skill Mahasiswa')
plt.xlabel('Nilai Rata-rata')

plt.show()

"""### Insight
Grafik menunjukkan bahwa rata-rata seluruh aspek soft skill mahasiswa, yaitu Kerja Tim, Kepemimpinan, Pemecahan Masalah, Komunikasi, Berpikir Kritis, dan Kreativitas, berada pada nilai yang hampir identik (sekitar 3,0). Hal ini mengindikasikan bahwa mahasiswa memiliki tingkat penguasaan soft skill yang relatif seimbang tanpa adanya kesenjangan yang signifikan antar kemampuan. Dengan demikian, tidak terdapat satu soft skill yang secara mencolok lebih unggul maupun lebih rendah dibandingkan yang lainnya.

### Distribusi Soft Skill
"""

plt.figure(figsize=(12,6))

Career_Recommendation_Cleaned_df[
    softskill
].boxplot()

plt.title('Distribusi Soft Skill')

plt.show()

"""### Insight
Boxplot menunjukkan bahwa seluruh aspek soft skill (Kepemimpinan, Komunikasi, Kerja Tim, Kreativitas, Berpikir Kritis, dan Pemecahan Masalah) memiliki pola distribusi yang hampir identik. Median masing-masing soft skill berada di sekitar nilai 3, dengan rentang nilai dari 1 hingga 5. Sebanyak 50% data berada pada rentang 2–4 (IQR), yang menunjukkan tingkat variasi yang moderat pada setiap aspek. Tidak terlihat adanya outlier yang signifikan, sehingga distribusi kemampuan soft skill mahasiswa relatif konsisten dan seimbang di seluruh kategori yang dianalisis.

## Analisis Pengalaman Mahasiswa

### Pengalaman Magang
"""

plt.figure(figsize=(5,4))

Career_Recommendation_Cleaned_df['Pengalaman_Magang'] \
    .value_counts() \
    .plot(kind='bar')

plt.title('Pengalaman Magang')
plt.xlabel('Status')
plt.ylabel('Jumlah')

plt.show()

"""### Insight
Sebagian besar mahasiswa memiliki pengalaman magang. Hal ini menunjukkan tingkat keterlibatan mahasiswa dalam dunia kerja profesional sebelum menyelesaikan pendidikan.

### Pengalaman Organisasi
"""

plt.figure(figsize=(5,4))

Career_Recommendation_Cleaned_df['Pengalaman_Organisasi'] \
    .value_counts() \
    .plot(kind='bar')

plt.title('Pengalaman Organisasi')
plt.xlabel('Status')
plt.ylabel('Jumlah')

plt.show()

"""### Insight
Mayoritas mahasiswa tidak memiliki pengalaman organisasi. Kondisi ini menunjukkan tingkat partisipasi mahasiswa dalam kegiatan non-akademik yang dapat membantu pengembangan soft skill dan kemampuan kepemimpinan.

### Pengalaman Kompetisi
"""

plt.figure(figsize=(5,4))

Career_Recommendation_Cleaned_df['Pengalaman_Kompetisi'] \
    .value_counts() \
    .plot(kind='bar')

plt.title('Pengalaman Kompetisi')
plt.xlabel('Status')
plt.ylabel('Jumlah')

plt.show()

"""### Insight
Mayoritas mahasiswa belum pernah mengikuti kompetisi, meskipun perbedaannya tidak terlalu signifikan dibandingkan mahasiswa yang pernah mengikuti kompetisi. Hal ini menunjukkan bahwa partisipasi dalam kegiatan kompetitif cukup baik, namun masih terdapat peluang untuk meningkatkan keterlibatan mahasiswa dalam ajang kompetisi.

## Analisis Jumlah Sertifikasi
"""

plt.figure(figsize=(8,5))

sns.histplot(
    data=Career_Recommendation_Cleaned_df,
    x='Jumlah_Sertifikasi',
    bins=15
)

plt.title('Distribusi Jumlah Sertifikasi')
plt.xlabel('Jumlah Sertifikasi')
plt.ylabel('Frekuensi')

plt.show()

"""### Insight
Mayoritas mahasiswa memiliki sekitar 3 sertifikasi, dengan distribusi jumlah sertifikasi yang relatif merata pada setiap kategori. Hal ini menunjukkan bahwa cukup banyak mahasiswa yang aktif mengikuti pelatihan atau program sertifikasi untuk meningkatkan kompetensi mereka, meskipun masih terdapat sebagian mahasiswa dengan jumlah sertifikasi yang rendah yang berpotensi untuk didorong mengikuti lebih banyak program pengembangan keterampilan.

## Analisis Tujuan Karir
"""

plt.figure(figsize=(10,5))

Career_Recommendation_Cleaned_df['Tujuan_Karier'] \
    .value_counts() \
    .plot(kind='bar')

plt.title('Distribusi Tujuan Karier')
plt.xlabel('Tujuan Karier')
plt.ylabel('Jumlah Mahasiswa')

plt.xticks(rotation=45)

plt.show()

"""### Insight
Mayoritas mahasiswa memilih jalur karier sebagai Spesialis, sementara Manajer menjadi pilihan yang paling sedikit diminati. Distribusi yang relatif merata menunjukkan bahwa mahasiswa memiliki preferensi karier yang beragam, dengan kecenderungan lebih besar pada pengembangan keahlian profesional dan teknis di bidang tertentu.

## Analisis Rekomendasi Karir
"""

plt.figure(figsize=(12,5))

Career_Recommendation_Cleaned_df['Rekomendasi_Karier'] \
    .value_counts() \
    .plot(kind='bar')

plt.title('Distribusi Rekomendasi Karier')
plt.xlabel('Rekomendasi Karier')
plt.ylabel('Jumlah Mahasiswa')

plt.xticks(rotation=45)

plt.show()

"""### Insight
Berdasarkan visualisasi distribusi rekomendasi karier, setiap kategori karier memiliki jumlah data yang relatif seimbang. Kondisi ini menunjukkan bahwa dataset telah mencakup berbagai jalur karier secara proporsional. Keseimbangan distribusi target seperti ini sangat baik untuk digunakan sebagai dasar pengembangan model AI karena dapat membantu model mempelajari setiap kategori karier dengan representasi data yang memadai.

## Analisis Korelasi Antar Fitur Numerik
"""

plt.figure(figsize=(10,8))

sns.heatmap(
    Career_Recommendation_Cleaned_df
        .select_dtypes(include='number')
        .corr(),
    annot=True,
    fmt='.2f'
)

plt.title('Korelasi Antar Fitur Numerik')

plt.show()

"""### Insight
Seluruh fitur numerik menunjukkan nilai korelasi yang sangat rendah (mendekati 0). Hal ini mengindikasikan bahwa tidak terdapat hubungan linear yang kuat antar variabel numerik dalam dataset. Dengan kata lain, setiap fitur seperti IPK, kemampuan soft skill, dan jumlah sertifikasi cenderung memberikan informasi yang berbeda dan saling melengkapi.

## Hubungan Jurusan dengan Rekomendasi Karir
"""

top_jurusan = (
    Career_Recommendation_Cleaned_df['Jurusan']
    .value_counts()
    .head(10)
    .index
)

cross = pd.crosstab(
    Career_Recommendation_Cleaned_df[
        Career_Recommendation_Cleaned_df['Jurusan'].isin(top_jurusan)
    ]['Jurusan'],
    Career_Recommendation_Cleaned_df[
        Career_Recommendation_Cleaned_df['Jurusan'].isin(top_jurusan)
    ]['Rekomendasi_Karier']
)

cross.plot(
    kind='bar',
    stacked=True,
    figsize=(14,6)
)

plt.title('Jurusan vs Rekomendasi Karier')
plt.xlabel('Jurusan')
plt.ylabel('Jumlah Mahasiswa')

plt.show()

"""### Insight
Setiap jurusan memiliki rekomendasi karier yang beragam, menunjukkan bahwa rekomendasi karier tidak hanya dipengaruhi oleh jurusan, tetapi juga oleh faktor lain seperti minat, soft skill, pengalaman, dan sertifikasi. Jurusan Hukum memiliki jumlah rekomendasi tertinggi karena jumlah mahasiswanya lebih banyak dibanding jurusan lainnya.

## Kesimpulan EDA
Berdasarkan hasil eksplorasi data, dataset menunjukkan keragaman yang baik dari sisi jurusan, bidang minat, pengalaman, soft skill, serta tujuan karier. Sebagian besar mahasiswa memiliki profil akademik dan non-akademik yang beragam, sehingga memberikan representasi yang cukup komprehensif untuk pengembangan sistem rekomendasi karier. Analisis korelasi menunjukkan bahwa beberapa kemampuan memiliki hubungan yang saling mendukung, sementara distribusi rekomendasi karier memperlihatkan variasi jalur karier yang dapat direkomendasikan berdasarkan karakteristik mahasiswa. Dataset ini telah siap digunakan sebagai dasar pengembangan model oleh tim AI.
"""

